- name: Install vim (Arch)
  become: yes
  pacman:
    name: vim
  when: ansible_distribution == "Archlinux"

- name: Install vim (Ubuntu)
  become: yes
  apt:
    name: vim
  when: ansible_distribution == "Ubuntu"

- name: Install vim (MacOSX)
  homebrew:
    name: vim
  when: ansible_distribution == "MacOSX"

- name: Link vimrc configuration
  file:
    src: "{{ playbook_dir }}/config/{{ item }}"
    dest: ~/.{{ item }}
    state: link
  with_items:
  - vimrc

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
